version: '3'
services:
  tf-jupiter:
    container_name: tf-jupiter-rcp217_final
    build: 
      context: .
      dockerfile: .DockerFile
    ports:
      - 8888:8888
    volumes:
      - .:/data
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]